# Support Vector Classifier Model

In [1]:
execution_mode = 'restricted'

## Table of Contents

- [Data Takeover](#Data-Takeover)
- [Support Vector Classifier](#Support-Vector-Classifier)
    - [Train/Test Split for Support Vector Classifier](#Train/Test-Split-for-Support-Vector-Classifier)
    - [Model Training for Support Vector Classifier](#Model-Training-for-Support-Vector-Classifier)
    - [Performance Measurement for Support Vector Classifier](#Performance-Measurement-for-Support-Vector-Classifier)
- [Support Vector Classifier with Cross-Validation](#Support-Vector-Classifier-with-Cross-Validation)
    - [Train/Test Split for Support Vector Classifier CV](#Train/Test-Split-for-Support-Vector-Classifier-CV)
    - [Model Training for Support Vector Classifier CV](#Model-Training-for-Support-Vector-Classifier-CV)
    - [Performance Measurement of Support Vector Classifier CV](#Performance-Measurement-of-Support-Vector-Classifier-CV)
- [Results Handover](#Results-Handover)

## Data Takeover

Read in DataFrame from chapter [Feature Matrix Generation](./3_FeatureMatrixGeneration.ipynb) as input for processing in this chapter.

In [2]:
import os
import pandas as pd

path_goldstandard = './daten_goldstandard'

# Restore results so far
df_labelled_feature_matrix = pd.read_pickle(os.path.join(path_goldstandard,
                                                         'labelled_feature_matrix.pkl'),
                                 compression=None)

df_attribute_with_sim_feature = pd.read_pickle(os.path.join(
    path_goldstandard, 'labelled_feature_matrix_full.pkl'), compression=None
                                              )

df_labelled_feature_matrix.head()

duplicates  coordinate_E_delta  coordinate_N_delta  corporate_full_delta  \
0           1                -1.0                -1.0                  -1.0   
1           1                -1.0                -1.0                  -1.0   
2           1                -1.0                -1.0                  -1.0   
3           1                -1.0                -1.0                  -1.0   
4           1                -1.0                -1.0                  -1.0   

   doi_delta  edition_delta  exactDate_delta  format_postfix_delta  \
0       -1.0           -1.0              1.0                   1.0   
1       -1.0           -1.0              1.0                   1.0   
2       -1.0           -1.0              1.0                   1.0   
3       -1.0           -1.0              1.0                   1.0   
4       -1.0           -1.0              1.0                   1.0   

   format_prefix_delta  isbn_delta  ...  musicid_delta  part_delta  \
0                  1.0         1.0  ...           -1.0         1.0   
1                  1.0         1.0  ...           -1.0         1.0   
2                  1.0         1.0  ...           -1.0         1.0   
3                  1.0         1.0  ...           -1.0         1.0   
4                  1.0         1.0  ...           -1.0         1.0   

   person_100_delta  person_245c_delta  person_700_delta  pubinit_delta  \
0               1.0           1.000000               1.0       1.000000   
1               1.0           0.818905              -0.5       0.848485   
2               1.0           0.697740              -0.5       0.848485   
3               1.0           0.818905              -0.5       0.848485   
4               1.0           1.000000              -1.0       1.000000   

   scale_delta  ttlfull_245_delta  ttlfull_246_delta  volumes_delta  
0         -1.0           1.000000               -1.0            1.0  
1         -1.0           0.787879               -1.0            1.0  
2         -1.0           1.000000               -1.0            1.0  
3         -1.0           0.787879               -1.0            1.0  
4         -1.0           1.000000               -1.0            1.0  

[5 rows x 21 columns]

In [3]:
print('Part of duplicates (1) on uniques (2) in units of [%]')
print(df_labelled_feature_matrix.duplicates.value_counts(normalize=True)*100)

Part of duplicates (1) on uniques (2) in units of [%]
0    99.435054
1     0.564946
Name: duplicates, dtype: float64


## Support Vector Classifier

A Support Vector Machine allows the use of regularization.

### Train/Test Split for Support Vector Classifier

The train/test split will be implemented here as a general function to be called in the models chapters.

In [4]:
import classifier_fitting_funcs as cff

X_tr, X_val, X_te, y_tr, y_val, y_te, idx_tr, idx_val, idx_te = cff.split_feature_target(
    df_labelled_feature_matrix, 'train_validation_test')

X_tr[:5], y_tr[:5], idx_tr[:5]

(array([[-1.        , -1.        , -0.5       , -1.        , -1.        ,
          0.5       ,  0.11111111,  0.        ,  0.        , -1.        ,
         -0.5       , -1.        , -0.5       ,  0.50833333,  0.52603359,
          0.51222697, -1.        ,  0.43181818, -1.        ,  0.        ],
        [-1.        , -1.        , -1.        , -1.        , -1.        ,
          0.75      ,  1.        ,  1.        ,  1.        , -1.        ,
         -1.        , -1.        ,  0.53721279,  0.61813782,  0.54661654,
         -0.5       , -1.        ,  0.59449891, -1.        ,  0.        ],
        [-1.        , -1.        , -0.5       , -0.5       , -1.        ,
          0.875     ,  0.42857143,  1.        ,  1.        , -1.        ,
         -1.        , -0.5       , -0.5       , -0.5       , -1.        ,
         -1.        , -1.        ,  0.53099238, -0.5       , -0.5       ],
        [-1.        , -1.        , -1.        , -1.        , -1.        ,
          0.25      ,  0.42857143, 

In [5]:
print(X_tr.shape, y_tr.shape, X_val.shape, y_val.shape, X_te.shape, y_te.shape)

(166868, 20) (166868,) (41718, 20) (41718,) (52147, 20) (52147,)


### Model Training for Support Vector Classifier

In [1]:
if execution_mode == 'full' :
    # Kernel 'rbf' has long calculation times, but does not generate
    #  the best accuracy : Ommit in grid search.
    parameter_dictionary = {
        'kernel' : ['linear', 'poly'],
        'degree' : [2, 3, 4],
        'gamma' : [1.5, 2, 2.5, 'auto'],
        'C' : [0.5, 0.7, 0.8, 0.9, 1.0],
        'class_weight' : [None]
    }
elif execution_mode == 'restricted' :
    parameter_dictionary = {
        'kernel' : ['poly'],
        'degree' : [3],
        'gamma' : [2.0],
        'C' : [0.5],
        'class_weight' : [None]
    }

# Grid of values
grid = cff.generate_parameter_grid(parameter_dictionary)

NameError: name 'execution_mode' is not defined

In [7]:
from sklearn.svm import SVC

sv = SVC(random_state=0)

# Save accuracy on test set
test_scores = []
for params_dict in grid :
    test_scores.append(cff.fit_model_measure_scores(sv, params_dict, X_tr, y_tr, X_val, y_val))

# Save measured accuracies
df_test_scores_sv = pd.DataFrame(test_scores).sort_values('accuracy_val', ascending=False)

Fitting with parameters {'C': 0.1, 'class_weight': None, 'degree': 3, 'gamma': 0.1, 'kernel': 'poly'}
 => validation score 99.851%


In [8]:
best_params = cff.get_best_parameters(test_scores, parameter_dictionary)

# Create a decision tree
sv_best = SVC(gamma=best_params['gamma'], kernel=best_params['kernel'],
              C=best_params['C'], class_weight=best_params['class_weight'],
              degree=best_params['degree'], random_state=0
             )

# Fit estimator
sv_best.fit(X_tr, y_tr)
y_pred_sv = sv_best.predict(X_te)

The parameters for the best model are ...
kernel = poly
degree = 3
gamma = 0.1
C = 0.1
class_weight = None


### Performance Measurement for Support Vector Classifier

In [9]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_te, y_pred_sv)

array([[51829,    23],
       [   64,   231]])

In [10]:
from sklearn.metrics import roc_auc_score, accuracy_score, precision_score, recall_score

print('Score {:.1f}%'.format(100*sv_best.score(X_te, y_te)))
print('Area under the curve {:.1f}% - accuracy {:.1f}% - precision {:.1f}% - recall {:.1f}%'.format(100*roc_auc_score(y_te, y_pred_sv),
                100*accuracy_score(y_te, y_pred_sv),
                100*precision_score(y_te, y_pred_sv),
                100*recall_score(y_te, y_pred_sv)
               ))

Score 99.8%
Area under the curve 89.1% - accuracy 99.8% - precision 90.9% - recall 78.3%


In [11]:
import results_analysis_funcs as raf

In [12]:
df_feature_base_full_te = df_attribute_with_sim_feature.iloc[idx_te]
df_feature_base_full_tr = df_attribute_with_sim_feature.iloc[idx_tr]

# Extend display to number of columns of DataFrame
pd.options.display.max_columns = len(df_feature_base_full_te.columns)

df_feature_base_full_te.sort_index().sample(n=20)

duplicates  coordinate_E_delta coordinate_E_x coordinate_E_y  \
54781            0                -1.0                                 
260050           0                -1.0                                 
7614             0                -1.0                                 
124622           0                -1.0                                 
32665            0                -1.0                                 
53100            0                -1.0                                 
129056           0                -1.0                                 
32346            0                -1.0                                 
73836            0                -1.0                                 
36150            0                -1.0                                 
74897            0                -1.0                                 
56263            0                -1.0                                 
128106           0                -1.0                                 
105768           0                -1.0                                 
131314           0                -1.0                                 
206727           0                -1.0                                 
38013            0                -1.0                                 
228563           0                -1.0                                 
93758            0                -1.0                                 
145527           0                -0.5                      e0080855   

        coordinate_N_delta coordinate_N_x coordinate_N_y  \
54781                 -1.0                                 
260050                -1.0                                 
7614                  -1.0                                 
124622                -1.0                                 
32665                 -1.0                                 
53100                 -1.0                                 
129056                -1.0                                 
32346                 -1.0                                 
73836                 -1.0                                 
36150                 -1.0                                 
74897                 -1.0                                 
56263                 -1.0                                 
128106                -1.0                                 
105768                -1.0                                 
131314                -1.0                                 
206727                -1.0                                 
38013                 -1.0                                 
228563                -1.0                                 
93758                 -1.0                                 
145527                -0.5                      n0460826   

        corporate_full_delta  \
54781                   -1.0   
260050                  -1.0   
7614                    -0.5   
124622                  -0.5   
32665                   -1.0   
53100                   -1.0   
129056                  -1.0   
32346                   -0.5   
73836                   -1.0   
36150                   -1.0   
74897                   -0.5   
56263                   -0.5   
128106                  -1.0   
105768                  -1.0   
131314                  -1.0   
206727                  -0.5   
38013                   -0.5   
228563                  -1.0   
93758                   -1.0   
145527                  -0.5   

                                         corporate_full_x  \
54781                                                       
260050                                                      
7614    bonne pioche (paris), buena vista internationa...   
124622         interkantonale lehrmittelzentrale (luzern)   
32665                                                       
53100                                                       
129056                                                      
32346                                                       
73836       

In [13]:
import results_saving_funcs as rsf

idx = {}
idx['true_predicted_uniques'], idx['true_predicted_duplicates'], idx['false_predicted_uniques'], idx['false_predicted_duplicates'] = raf.get_confusion_matrix_indices(y_te, y_pred_sv)

wrong_prediction_groups = ['false_predicted_uniques', 'false_predicted_duplicates']

for i in wrong_prediction_groups :
    rsf.add_wrong_predictions(path_goldstandard, 
                              sv_best, i, df_feature_base_full_te.loc[idx[i]])

## Support Vector Classifier with Cross-Validation

### Train/Test Split for Support Vector CV

In [14]:
X_tr, _, X_te, y_tr, _, y_te, idx_tr, _, idx_te = cff.split_feature_target(
    df_labelled_feature_matrix, 'train_test')

X_tr[:5], y_tr[:5], idx_tr[:5]

(array([[-1.        , -1.        , -1.        , -1.        , -1.        ,
          0.5       ,  0.42857143,  0.        ,  1.        , -1.        ,
         -0.5       , -0.5       , -0.5       ,  0.50165426, -0.5       ,
          0.48593074, -1.        ,  0.60439973, -1.        ,  0.        ],
        [-1.        , -1.        , -0.5       , -1.        , -1.        ,
          0.25      ,  0.42857143,  0.        ,  0.        , -1.        ,
         -1.        , -1.        , -0.5       ,  0.54435379, -1.        ,
         -0.5       , -1.        ,  0.54177001, -1.        , -0.5       ],
        [-1.        , -1.        , -0.5       , -1.        , -1.        ,
          0.25      ,  1.        ,  1.        ,  0.        , -1.        ,
         -1.        , -0.5       , -0.5       ,  0.6020276 ,  0.53663004,
          0.49448622, -1.        ,  0.57046955, -1.        , -0.5       ],
        [-1.        , -1.        , -1.        , -1.        , -1.        ,
          0.75      ,  1.        , 

In [15]:
print(X_tr.shape, y_tr.shape, X_te.shape, y_te.shape)

(208586, 20) (208586,) (52147, 20) (52147,)


### Model Training for Support Vector CV

In [16]:
from sklearn.model_selection import GridSearchCV
import numpy as np

# Create cross-validation object with DecisionTreeClassifer
grid_cv = GridSearchCV(SVC(random_state=0),
                       param_grid = parameter_dictionary, cv=5
                       , verbose=1
                      )

# Fit estimator
grid_cv.fit(X_tr, y_tr)

# Get the results with 'cv_results_', get parameters with their scores
params = pd.DataFrame(grid_cv.cv_results_['params'])
scores = pd.DataFrame(grid_cv.cv_results_['mean_test_score'], columns=['accuracy_val'])
log_scores = pd.DataFrame(np.log(1-grid_cv.cv_results_['mean_test_score']), columns=['log_accuracy_val'])
scores_std = pd.DataFrame(grid_cv.cv_results_['std_test_score'], columns=['std_accuracy_val'])

# Create a DataFrame of (parameters, score, std) pairs
df_test_scores_svcv = params.merge(scores, how='inner', left_index=True, right_index=True)
df_test_scores_svcv = df_test_scores_svcv.merge(
    scores_std, how='inner', left_index=True, right_index=True).sort_values(
    'accuracy_val', ascending=False)
df_test_scores_svcv = df_test_scores_svcv.merge(
    log_scores, how='inner', left_index=True, right_index=True)

Fitting 5 folds for each of 1 candidates, totalling 5 fits


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:   33.9s finished


In [17]:
df_test_scores_svcv

C class_weight  degree  gamma kernel  accuracy_val  std_accuracy_val  \
0  0.1         None       3    0.1   poly      0.998351          0.000143   

   log_accuracy_val  
0         -6.407464

In [18]:
svcv_best = grid_cv.best_estimator_
y_pred_svcv = svcv_best.predict(X_te)

### Performance Measurement of Support Vector Classifier CV

In [19]:
confusion_matrix(y_te, y_pred_svcv)

array([[51829,    23],
       [   60,   235]])

In [20]:
print('Score {:.1f}%'.format(100*svcv_best.score(X_te, y_te)))
print('Area under the curve {:.1f}% - accuracy {:.1f}% - precision {:.1f}% - recall {:.1f}%'.format(
    100*roc_auc_score(y_te, y_pred_svcv),
                100*accuracy_score(y_te, y_pred_svcv),
                100*precision_score(y_te, y_pred_svcv),
                100*recall_score(y_te, y_pred_svcv)
               ))

Score 99.8%
Area under the curve 89.8% - accuracy 99.8% - precision 91.1% - recall 79.7%


In [21]:
idx = {}
idx['true_predicted_uniques'], idx['true_predicted_duplicates'], idx['false_predicted_uniques'], idx['false_predicted_duplicates'] = raf.get_confusion_matrix_indices(y_te, y_pred_svcv)

wrong_prediction_groups = ['false_predicted_uniques', 'false_predicted_duplicates']

for i in wrong_prediction_groups :
    rsf.add_wrong_predictions(path_goldstandard, 
                              svcv_best, i, df_feature_base_full_te.loc[idx[i]], '_CV')

## Results Handover

In [22]:
rsf.add_result_to_results(path_goldstandard,
                          df_test_scores_sv, sv_best, X_te, y_te, y_pred_sv)
rsf.add_result_to_results(path_goldstandard, 
                          df_test_scores_svcv, svcv_best, X_te, y_te, y_pred_svcv, '_CV')